import React, { useEffect, useState } from 'react';
import './NewsFeed.css'; // Optional CSS styling file

function NewsFeed() {
  const [news, setNews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedCategory, setSelectedCategory] = useState('All');

  useEffect(() => {
    // Fetch JSON file generated by Python scraper
    fetch('/news_data.json')
      .then(response => {
        if (!response.ok) {
          throw new Error('Failed to load news data');
        }
        return response.json();
      })
      .then(data => {
        setNews(data);
        setLoading(false);
      })
      .catch(err => {
        console.error('Error loading news:', err);
        setError('Failed to load news feed. Please run the Python scraper first.');
        setLoading(false);
      });
  }, []);

  // Filter categories
  const categories = ['All', ...new Set(news.map(item => item.category).filter(Boolean))];
  const filteredNews = selectedCategory === 'All' 
    ? news 
    : news.filter(item => item.category === selectedCategory);

  if (loading) {
    return (
      <div className="news-loading">
        <div className="spinner"></div>
        <p>Loading Daily FT Live News Feed...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="news-error">
        <p>⚠️ {error}</p>
      </div>
    );
  }

  return (
    <div className="news-container">
      <header className="news-header">
        <h2>📰 Daily FT Live Business Feed</h2>
        <span className="news-count">{filteredNews.length} Articles Live</span>
      </header>

      {/* Category Filter Pills */}
      <div className="category-filter">
        {categories.map((cat, idx) => (
          <button 
            key={idx} 
            className={`filter-btn ${selectedCategory === cat ? 'active' : ''}`}
            onClick={() => setSelectedCategory(cat)}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* News Cards Grid */}
      <div className="news-grid">
        {filteredNews.map((item, index) => (
          <div key={index} className="news-card">
            <div className="news-image-wrapper">
              <img 
                src={item.image || 'https://via.placeholder.com/600x400?text=Daily+FT'} 
                alt={item.title}
                onError={(e) => {
                  e.target.onerror = null;
                  e.target.src = 'https://via.placeholder.com/600x400?text=Daily+FT+News';
                }} 
              />
              {item.category && (
                <span className="category-badge">{item.category}</span>
              )}
            </div>
            <div className="news-card-content">
              <h3>
                <a href={item.link} target="_blank" rel="noopener noreferrer">
                  {item.title}
                </a>
              </h3>
              <a href={item.link} target="_blank" rel="noopener noreferrer" className="read-more-link">
                Read Full Story on FT.lk &rarr;
              </a>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default NewsFeed;
